### ISSUE TITLE
Reader sends points with invalid `time` field into the flowgraph

### ISSUE THREAD

**Issue by dmajda** [juttle/juttle-sql-adapter-common#9]
This causes problems downstream, as observed in juttle/juttle#98:

```
$ time juttle -e "read sqlite -table 'my_table' |  put c = count() by my_field | (tail 1; write elastic -index_prefix 'gha_test' -index_interval 'none')"     
[2016-01-04 11:15:10.936] [INFO] juttle-adapter - loaded elastic
[2016-01-04 11:15:11.380] [INFO] juttle-adapter - loaded sqlite
Unhandled rejection TypeError: Cannot read property 'milliseconds' of undefined
    at /Users/henridf/.nvm/versions/node/v4.2.2/lib/node_modules/juttle/lib/runtime/procs/tail.js:65:31
    at /Users/henridf/.nvm/versions/node/v4.2.2/lib/node_modules/juttle/node_modules/underscore/underscore.js:380:19
    at Function._.map._.collect (/Users/henridf/.nvm/versions/node/v4.2.2/lib/node_modules/juttle/node_modules/underscore/underscore.js:172:24)
    at Function._.sortBy (/Users/henridf/.nvm/versions/node/v4.2.2/lib/node_modules/juttle/node_modules/underscore/underscore.js:376:22)
    at fanin.extend.emit_ordered_points (/Users/henridf/.nvm/versions/node/v4.2.2/lib/node_modules/juttle/lib/runtime/procs/tail.js:62:24)
    at fanin.extend._run (/Users/henridf/.nvm/versions/node/v4.2.2/lib/node_modules/juttle/lib/runtime/procs/tail.js:38:14)
    at fanin.extend.eof (/Users/henridf/.nvm/versions/node/v4.2.2/lib/node_modules/juttle/lib/runtime/procs/tail.js:47:14)
    at base.extend.consume_eof (/Users/henridf/.nvm/versions/node/v4.2.2/lib/node_modules/juttle/lib/runtime/procs/fanin.js:95:18)
    at Base.extend.emit_eof (/Users/henridf/.nvm/versions/node/v4.2.2/lib/node_modules/juttle/lib/runtime/procs/base.js:208:25)
    at oops_fanin.extend.eof (/Users/henridf/.nvm/versions/node/v4.2.2/lib/node_modules/juttle/lib/runtime/procs/put.js:125:14)
    at base.extend.consume_eof (/Users/henridf/.nvm/versions/node/v4.2.2/lib/node_modules/juttle/lib/runtime/procs/fanin.js:95:18)
    at Base.extend.emit_eof (/Users/henridf/.nvm/versions/node/v4.2.2/lib/node_modules/juttle-sqlite-adapter/node_modules/juttle/lib/runtime/procs/base.js:208:25)
    at Base.extend.eof (/Users/henridf/.nvm/versions/node/v4.2.2/lib/node_modules/juttle-sqlite-adapter/node_modules/juttle/lib/runtime/procs/base.js:171:14)
    at /Users/henridf/.nvm/versions/node/v4.2.2/lib/node_modules/juttle-sqlite-adapter/node_modules/juttle-sql-adapter-common/lib/read.js:237:18
    at Object.finallyHandler (/Users/henridf/.nvm/versions/node/v4.2.2/lib/node_modules/juttle-sqlite-adapter/node_modules/knex/node_modules/bluebird/js/main/finally.j
```

The `tail` proc (and probably other code) [expects](https://github.com/juttle/juttle/blob/master/lib/runtime/procs/tail.js#L63-L69) that the `time` field either isn’t present at all or contains a valid `JuttleMoment` instance.

**Comment by VladVega** [comment]
I believe this issue will be solved by https://github.com/juttle/juttle/pull/227 eventually.

**Comment by VladVega** [comment]
@dmajda @demmer So I guess this is a problem when https://github.com/juttle/juttle/blob/master/lib/runtime/juttle-utils.js#L28 doesn't produce a valid moment. I know there was some time conversation between you guys today - anything on this?

**Comment by dmajda** [comment]
When a valid moment can’t be produced, the adapter should emit a warning and drop the point.

Not dropping a point would mean the invariant that the `time` field either isn’t present or holds a valid `JuttleMoment` instance would be violated. Not emitting a warning would lead to silent data loss.
